### ISSUE TITLE
Lack of /usr/bin/ directory during sh symlink creation

### ISSUE THREAD

**Issue by CrossScarDev** [malwarepad/cavOS#15]
When running `make tools` it fails expecting autotools 2.69 but the latest version (available on arch) is 2.79 making it impossible to build with arch. I will try to make a docker container to remedy the problem and submit a pull request if I can.

Here is the error:
```
aclocal.m4:17: warning: this file was generated for autoconf 2.69.
You have another version of autoconf.  It may work, but is not guaranteed to.
If you have problems, you may need to regenerate the build system entirely.
To do so, use the procedure documented by the package, typically 'autoreconf'.
configure.ac:21: error: Please use exactly Autoconf 2.69 instead of 2.72.
../config/override.m4:12: _GCC_AUTOCONF_VERSION_CHECK is expanded from...
configure.ac:21: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
automake: error: autoconf failed with exit status: 1
make[1]: *** [Makefile:71: tools] Error 1
make[1]: Leaving directory '/home/crossscar/cavOS/src/kernel'
make: *** [Makefile:61: tools] Error 2
```

**Comment by malwarepad** [comment]
No, a specialized environment is not needed, hence docker is not needed. The toolchain build scripts will **compile that version of autotools for you** and put it in a directory under `~/opt/`. That is, if you're building an up-to-date version of the source tree. Make sure that is the case by doing `git pull` `make clean` and finally ensure no cross or autotools directories exist under `~/opt/` so `make tools` does everything in a clean matter.

**Comment by CrossScarDev** [comment]
Thank you this has fixed the problem.

**Comment by CrossScarDev** [comment]
Never mind now when I run `make disk` I get the following error:
```
+ ln -s bash /home/crossscar/cavOS/tools/userland/../../target/usr//bin/sh
ln: failed to create symbolic link '/home/crossscar/cavOS/tools/userland/../../target/usr//bin/sh': No such file or directory
make: *** [Makefile:21: ports] Error 1
```
