### ISSUE TITLE
Would you be open to relicensing this under MIT/3BSD/The Unlicense/WTFPL/CC0?

### ISSUE THREAD

**Issue by xplshn** [malwarepad/cavOS#17]
Hi, 1st of all, great project, been following its development since its inception, have you tought of using a more permissive license? Be it copyrighted or entirely public domain, it'd be better than a license completely incompatible with others, one cannot even import a cavOS header in other projects due to the GPL, nor is people allowed to distribute statically linked binaries containing any sort of code that comes from this repo, its really a shame, because your work is amazing, specially for other people doing osdev, it works as a great reference and starting point for other OSdev projects.

Thanks for taking this into consideration!

**Comment by malwarepad** [comment]
I appreciate the interest for this project, but I don't plan on changing the GPL license to anything else.
