### ISSUE TITLE
About the project's direction... Why not Plan9-ify it?

### ISSUE THREAD

**Issue by xplshn** [malwarepad/cavOS#18]
Per-process namespaces + Everything is really a file, would allow for so much flexibility...
For example, in Plan 9, if you wanted to remote access another Plan 9 machine, all you'd do is bind your network card to the other machine's in a namespace, then you'd start `rio` within that namespace (think of Rio like Sway, a WM and graphical stack, it needs no server unlike Xorg).

In plan 9, everything is a file, and thus, everything can be networked
Not only that, but every process has its own namespace, with access to different filesystems (the physical files exist on cuefs, the actual disk, everything else are virtual filesystems offering direct access to the network stack, to processes, to devices, to device abstractions, to GPIO, there's even a filesystem for Rio, that lets you direct where windows are placed, and etc)

Plan 9 is a modern OS, unlike Unix, I think Unix is great, but why keep repeating the mistakes of the past, which were standarized as POSIX just for compat...

Love the project, btw, just think that it could be so much more than just another Minix, another Unix clone.

**Comment by malwarepad** [comment]
That's a pretty unique idea, but really really out of scope. I'm not familiar with the plan9 OS layout and don't want to follow whatever it is. I also appreciate the simplicity of Unix and enjoy porting applications directly from Linux with minimal overhead.
