### ISSUE TITLE
`make tools` does nothing on Ubuntu 23.04

### ISSUE THREAD

**Issue by ajh123** [malwarepad/cavOS#2]
On Ubuntu 23.04 after cloning the repository and running a `make tools` the make programs returns `make: 'tools' is up to date` without installing any tools. I've installed the dependencies with the `sudo apt install build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libisl-dev parted dosfstools` provided.

**Comment by malwarepad** [comment]
Fixed by commit https://github.com/malwarepad/cavOS/commit/3988e18bd41d30be7eaf19661e12e6ac75cc8998

**Comment by ajh123** [comment]
I can confirm it has been fixed.
